---
- hosts: malawitest
  gather_facts: yes
  sudo: yes
  vars_files:
    - ./group_vars/site.yml
  
  roles:
    - williamyeh.oracle-java

  vars:
    - java_version: 7
    - java_subversion: 80
    - java_download_path: /tmp
    - java_download_from_oracle: true
    - java_remove_download: false

  tasks:
  - name: install required packages
    apt: name={{ item }} state=present install_recommends=yes force=yes
    with_items:
        - unzip
        - tar
        - wget
        - maven
        - git     
    register: report    
    ignore_errors: true    

  - name: apt install results
    debug: msg="{{ item.item }}"
    with_items: "{{ report.results }}"
    when: item.changed == true

  - name: get the latest code from github
    git: repo="{{ git_repo_url }}" dest="/tmp/{{ git_repo_name }}" update=yes force=yes

  - name: build the distro
    shell: mvn clean install -DskipTests -Pdistribution    
    always_run: true
    args: 
      chdir: /tmp/{{ git_repo_name }}
    register: build_output  

  - name: Find the distro zip file    
    find: 
      paths: /tmp/{{ git_repo_name }}/distro/target
      patterns: "*distro.zip"
    register: distro_file  

  - name: print info about the distro file
    debug: msg="{{ distro_file.files }}"

  - name: Unzip the distro file
    unarchive: src="{{ item.path }}" dest=/tmp/ copy=no list_files=yes
    with_items: "{{ distro_file.files }}"
    register: unzip_files
